services:
  db:
    image: postgres:latest
    container_name: library_db
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=library_db
    ports: 
        - "5432:5432"
    restart: always
    volumes:
        - db_data:/var/lib/postgresql/data
volumes:
    db_data: